name: Build and Deploy Documentation

on:
  push:
    branches: [ main ]
    paths:
      - 'software/**'
      - 'hardware/**'
      - 'README.md'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    environment:
      name: github-pages

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup mdBook
      uses: peaceiris/actions-mdbook@v1
      with:
        mdbook-version: '0.4.52'

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Google Chrome
      run: |
        wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    - name: Build Documentation
      run: |
        # Build mdBook
        cd software/scripts && python3 build_docs.py
        cd ../../
        
        # Generate professional docs
        cd software/documentation && python3 generate_professional_pdf.py
        cd ../../
        
        # Prepare docs directory
        cp -r software/book/book/* docs/mdbook/
        cp software/documentation/build/datasheet_professional.html docs/
        find software/documentation/build -name "*.png" -o -name "*.jpg" -o -name "*.pdf" -exec cp {} docs/ \;

    - name: Setup Pages
      uses: actions/configure-pages@v3

    - name: Upload Pages artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: docs

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2
